spring:
  application:
    name: system-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restaurant_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: qaz98188729
  data:
    redis:
      url: redis://localhost:6379
      password: qaz98188729
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.systembackend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl